Repository wp-cli/shell-command, pull requests merged in 2019-04, with the labels that each got.

#33 Add possibility to change the shell binary
  features/shell.feature
  src/WP_CLI/REPL.php
Labels: command:shell

#37 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#39 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#40 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  phpcs.xml.dist
  shell-command.php
  src/Shell_Command.php
  src/WP_CLI/Shell/REPL.php
Labels: scope:testing
